# Generated by Django 6.0.6 on 2026-07-08 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('runtime', models.PositiveIntegerField(help_text='Runtime in minutes')),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('cast', models.TextField(help_text='Comma-separated cast members')),
                ('director', models.CharField(max_length=100)),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube URL, e.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ', null=True)),
                ('is_currently_playing', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='movies', to='myproject.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myproject.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('screen', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='myproject.movie')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('seats', models.CharField(help_text='Comma-separated seat codes, e.g. A3,A4', max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myproject.showtime')),
            ],
        ),
    ]
